### ISSUE TITLE
Новая книга

### ISSUE THREAD

**Issue by ilyaBykonya** [JoshuaJakowlew/cppfaq#26]
Нашёл вот такую неплохую книгу. Как первая книга по многопоточке она не годится, но для тех, кто уже читал того же Уильямса очень годно.

[Grimm_R_Parallelnoe_programmirovanie_na_C.pdf](https://github.com/JoshuaJakowlew/cppfaq/files/9173182/Grimm_R_Parallelnoe_programmirovanie_na_C.pdf)

**Comment by ansa-sequence** [comment]
@Reavolt Мог ли ты добавить данную книгу в общую библиотеку книг?
Спасибо.

**Comment by Reavolt** [comment]
@ansa-sequence Так уже лежит. https://disk.yandex.ru/i/NxWU7kecLwOXUw
