### ISSUE TITLE
Онлайн-ресурс для новичков

### ISSUE THREAD

**Issue by grigabyte** [JoshuaJakowlew/cppfaq#31]
**https://learncpp.com** — отличный ресурс для изучения C++, если ты полный 0 в программировании. Помимо самого синтаксиса, автор оставляет рекомендации и лучшие / худшие практики программирования как на языке cpp, так и вообще.

На ресурсе есть поддержка комментариев, где люди обсуждают возникающие проблемы. Лекции постоянно обновляются и дополняются.

Язык ресурса — английский, но этот барьер можно легко преодолеть с помощью любого переводчика страниц.

**Comment by JoshuaJakowlew** [comment]
Добавил, спасибо за рекомендацию.
