### ISSUE TITLE
Доступ к циклу "Полное руководство по CMake"

### ISSUE THREAD

**Issue by mrmomenticus** [JoshuaJakowlew/cppfaq#33]
Автор заблокирован или удален, из-за этого доступа к циклу нет, ссылки не актуальны. [Ссылка](https://habr.com/ru/articles/432096/)

**Comment by JoshuaJakowlew** [comment]
Удалил, спасибо. Если эти статьи есть где-то вне хабра, буду признателен за ссылку.

**Comment by mrmomenticus** [comment]
@JoshuaJakowlew 
Нашел у "заимствующих" ребят, ссылаются на статьи из хабра.
[Часть 1](https://www.pvsm.ru/kompilyatsiya/300549)
[Часть 2](https://www.pvsm.ru/kompilyatsiya/301178)
[Часть 3](https://www.pvsm.ru/kompilyatsiya/302892)

Также одну из частей в интернет архиве
[Архив] (https://web.archive.org/web/20220528140444/https://habr.com/en/post/432096/)
