### ISSUE TITLE
Добавьте в книги 

### ISSUE THREAD

**Issue by kompilainenn** [JoshuaJakowlew/cppfaq#38]
для начинающих - Дейтел. С++20 для программистов
для продвинутых - Гримм. С++20 в деталях

**Comment by kompilainenn** [comment]
Дейтел. С++20 для программистов - https://disk.yandex.com/i/e5XHq9pxUWRWiw

Гримм. С++20 в деталях - https://disk.yandex.com/i/NpeEyVigmF2SPA

**Comment by ansa-sequence** [comment]
Fixed int #9
